### ISSUE TITLE
Call to get coin's OHLC (Open High Low Close)

### ISSUE THREAD

**Issue by AlleCristo** [Philipinho/CoinGecko-Java#35] opened 2022-03-25 11:14 UTC
Hi!
I am having some problems with the call to get OHLC of a given coin.

Since I didn't find this method in this project I tried to implement it following the current project style,
but I get the following error: CoinGeckoApiError(code=500, message=Internal Server Error)

I also tried to execute the call via URL from the Browser and it returns the requested values, so I think I've done something wrong in the Implementation. 

Call By URL: https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=1

Code added in CoinGeckoApiService.java
![s1](https://user-images.githubusercontent.com/68555033/160110423-44a72aab-0fda-4293-9ebc-7932bf43e5a0.png)

Code added in CoinGeckoApiClient.java
![s2](https://user-images.githubusercontent.com/68555033/160110425-39c93cb8-93b1-43ff-9f87-38dfff883530.png)

Code added in CoinGeckoApiClientImpl.java
![s3](https://user-images.githubusercontent.com/68555033/160110426-b2c068f3-4d59-41e4-90e3-d4dfac92e96a.png)

Code used in a main to Test the implementation
![s4](https://user-images.githubusercontent.com/68555033/160110427-a15030d8-9551-4cce-95b6-50ab80a515f2.png)

Error obtained
![s5](https://user-images.githubusercontent.com/68555033/160110429-3fddb58d-9639-4785-832a-2c251f60a812.png)

**Comment by Philipinho** [comment] 2022-03-25 18:15
I just made an official implementation. Please try out [implement_coin_OHLC](https://github.com/Philipinho/CoinGecko-Java/tree/implement_coin_OHLC) branch and give me feedback.

**Comment by belohnung** [comment] 2022-03-27 15:49
So far no issues with the endpoint, thanks :3

**Comment by AlleCristo** [comment] 2022-03-27 18:59
Thank you so much for the response!

As you can see from the attached images I implemented it exactly the same way, but I realized only today that I made a distracting mistake...
I misspelled the name of the method getCoinOHLC by writing getCoinOTHL

Anyway, now everything works perfectly!
Thanks a lot again and I hope I've been helpful for this repo, even if in a very small part!

**Comment by Philipinho** [comment] 2022-03-27 21:27
Thank you all for confirming it works as intended.
The branch has been merged.

**Closed by Philipinho** 2022-03-27 21:27 UTC
